In [1]:
from sklearn import tree
import pandas as pd
import numpy as np
import jieba.analyse#用于分词
from sklearn.model_selection import train_test_split#用于分割数据集
from sklearn.feature_extraction.text import TfidfVectorizer#用于特征提取
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# 读取数据
data=pd.read_excel('社会科学标题数据集-200/data_200_each_discipline.xlsx')
data.columns = ['ID','Title','Subject']
print(data.head())
# 读取title数据
title_list=data['Title'].tolist()
print(title_list[0:10])
# 所有类别(重复)
category_list=data['Subject'].tolist()



   ID                    Title Subject
0   0     甲午中日战争至甲辰日俄战争期间东北亚局势    人文地理
1   1           以事业为己任——记周光复教授    人文地理
2   2         大饥荒年代非正常死亡的另一种计算    人文地理
3   3               鲁迅小说中的女性世界    人文地理
4   4  基于语料库的英汉光亮类词语研究：认知语义学视角    人文地理
['甲午中日战争至甲辰日俄战争期间东北亚局势', '以事业为己任——记周光复教授', '大饥荒年代非正常死亡的另一种计算', '鲁迅小说中的女性世界', '基于语料库的英汉光亮类词语研究：认知语义学视角', '按摩院里盲人师傅的心酸幽默话', '骆家辉:开动美国经济引擎的华裔部长', '南北朝时期民族迁移引起的语音变迁——以晋代吴方言的韵母为例', '宋代女性文学中食物意象的审美文化阐释——评《华夏饮食文化》', '一举多得的“城市作业本”']


In [2]:
#所有类别
category=(list(set(category_list)))
print(category)

['政治学', '语言学', '新闻传播学', '体育学', '文学', '经济学', '心理学', '法学', '图书馆、情报与文献学', '宗教学', '教育学', '民族学', '环境科学', '马克思主义', '历史学', '人文地理', '考古学', '哲学', '艺术学', '社会学', '统计学', '管理学']


In [3]:
with open ('stop.txt','r',encoding='utf-8') as f:
    stopwords=f.read()
    stopwords=stopwords.split('\n')
#分词
title_list_cut=[]
for title in title_list:
    word=jieba.lcut(title)
    if word not in stopwords:
        title_list_cut.append(' '.join(word))
print(title_list_cut[0:10])
print(category_list[0:10])

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\jieba.cache
Loading model cost 1.169 seconds.
Prefix dict has been built successfully.


['甲午 中日战争 至 甲辰 日俄战争 期间 东北亚 局势', '以 事业 为 己任 — — 记周 光复 教授', '大 饥荒 年代 非正常 死亡 的 另 一种 计算', '鲁迅 小说 中 的 女性 世界', '基于 语料库 的 英汉 光亮 类 词语 研究 ： 认知 语义学 视角', '按摩院 里 盲人 师傅 的 心酸 幽默 话', '骆家辉 : 开动 美国 经济 引擎 的 华裔 部长', '南北朝 时期 民族 迁移 引起 的 语音 变迁 — — 以 晋代 吴方言 的 韵母 为例', '宋代 女性 文学 中 食物 意象 的 审美 文化 阐释 — — 评 《 华夏 饮食文化 》', '一举多得 的 “ 城市 作业本 ”']
['人文地理', '人文地理', '人文地理', '人文地理', '人文地理', '人文地理', '人文地理', '人文地理', '人文地理', '人文地理']


In [5]:
# 进行数据分割
x_train,x_test,y_train,y_test=train_test_split(title_list_cut,category_list,test_size=0.3,random_state=22)
# 对数据集进行特征抽取
tf = TfidfVectorizer(stop_words=stopwords)
x_train = tf.fit_transform(x_train)
x_test = tf.transform(x_test)


# 对数据集进行特征选择
f_classif(x_train,y_train)
selector = SelectKBest(f_classif, k=5000)
selector.fit(x_train, y_train)
x_train = selector.transform(x_train)
x_test = selector.transform(x_test)

print(x_train.shape)



        






(3080, 5000)


d:\Python\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['exp', 'lex', '①①', '①②', '①③', '①④', '①⑤', '①⑥', '①⑦', '①⑧', '①⑨', '①ａ', '①ｂ', '①ｃ', '①ｄ', '①ｅ', '①ｆ', '①ｇ', '①ｈ', '①ｉ', '①ｏ', '②①', '②②', '②③', '②④', '②⑤', '②⑥', '②⑦', '②⑧', '②⑩', '②ａ', '②ｂ', '②ｄ', '②ｅ', '②ｆ', '②ｇ', '②ｈ', '②ｉ', '②ｊ', '③①', '③⑩', '③ａ', '③ｂ', '③ｃ', '③ｄ', '③ｅ', '③ｆ', '③ｇ', '③ｈ', '④ａ', '④ｂ', '④ｃ', '④ｄ', '④ｅ', '⑤ａ', '⑤ｂ', '⑤ｄ', '⑤ｅ', '⑤ｆ', '１２', 'ｌｉ', 'ｚｘｆｉｔｌ'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


In [6]:
# 决策树
dtc=tree.DecisionTreeClassifier()
dtc.fit(x_train,y_train)

dtc.score(x_test,y_test)


0.3181818181818182

In [7]:
dtc.score(x_train,y_train)

0.9811688311688311

In [8]:
param_grid={
    'criterion':['gini','entropy'],
    'max_depth':[10,15]
}
GR=GridSearchCV(tree.DecisionTreeClassifier(),param_grid,cv=5)
GR.fit(x_train,y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=None,
             param_grid={'criterion': ['gini', 'entropy'],
                   

In [9]:
GR.best_params_

{'criterion': 'gini', 'max_depth': 15}

In [10]:
GR.best_score_

0.16428571428571428

In [11]:
#最优模型
dtc=tree.DecisionTreeClassifier(criterion='gini',max_depth=15)
dtc.fit(x_train,y_train)
dtc.score(x_test,y_test)

0.16893939393939394

In [12]:
dtc.score(x_train,y_train)

0.2237012987012987

In [13]:
y_true=y_test
y_pred=dtc.predict(x_test)



print(confusion_matrix(y_true,y_pred,labels=category))

[[11  0  0  0  4  0  0  0  2  0  1  1  0  1  0  0 40  0  0  0  0  2]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0 50  0  0  0  0  0]
 [ 2  0 11  0  1  0  0  0  0  0  1  0  0  1  0  0 41  0  0  0  0  0]
 [ 0  0  0 15  0  0  1  0  0  0  1  0  0  0  0  0 35  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0 70  0  0  0  0  0]
 [ 0  0  1  0  0  1  0  0  0  0  0  0  0  2  0  0 54  0  0  0  0  2]
 [ 0  0  0  0  0  0 11  0  0  0  2  0  0  0  0  0 52  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 10  0  0  0  0  0  0  1  0 52  0  0  0  0  1]
 [ 0  0  1  0  0  0  0  2 17  0  0  0  0  0  0  0 40  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  5  0  1  0  0  0  0 43  0  0  0  0  1]
 [ 0  0  0  0  0  0  1  0  0  0 21  0  0  2  0  0 37  1  0  1  0  0]
 [ 1  0  1  0  0  0  0  0  0  0  2 12  0  0  0  0 44  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  4  1  1  0  0  0 55  0  0  0  0  3]
 [ 4  0  0  0  0  0  0  0  0  0  0  1  0 24  0  0 25  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  1

In [14]:
print(classification_report(y_true,y_pred,labels=category))

              precision    recall  f1-score   support

         政治学       0.48      0.18      0.26        62
         语言学       0.00      0.00      0.00        51
       新闻传播学       0.52      0.19      0.28        57
         体育学       1.00      0.29      0.45        52
          文学       0.00      0.00      0.00        74
         经济学       0.50      0.02      0.03        60
         心理学       0.65      0.17      0.27        65
          法学       0.77      0.16      0.26        64
  图书馆、情报与文献学       0.85      0.28      0.42        60
         宗教学       0.83      0.09      0.17        53
         教育学       0.57      0.33      0.42        63
         民族学       0.46      0.20      0.28        61
        环境科学       1.00      0.02      0.03        64
       马克思主义       0.60      0.44      0.51        54
         历史学       0.00      0.00      0.00        56
        人文地理       0.00      0.00      0.00        71
         考古学       0.05      1.00      0.10        55
          哲学       0.00    

d:\Python\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
